# Generated by Django 3.0.2 on 2020-01-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_telefonica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_empresa', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('telefone_de_contato', models.CharField(max_length=14)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
